Thomas/fa qpage
TranTerrence/IVGC-alumni-website pull request #4
Opened 2020-11-13 19:35 UTC by Th-omas

Ajout de la page FAQ
Reste à faire:
- Requête des questions sur firestore

2020-11-13 19:59 UTC, TranTerrence requested changes
On essai de garder le theme clean, on evite de push des styles non utilisés

2020-11-13 19:59 UTC, TranTerrence commented on src/pages/FAQPage.tsx
> +  secondaryHeading: {
N'est pas utilisé dans le code

2020-11-13 19:59 UTC, TranTerrence commented on src/pages/FAQPage.tsx
> +  icon: {
N'est pas utilisé dans le code non plus

2020-11-13 19:59 UTC, TranTerrence commented on src/pages/FAQPage.tsx
> +  details: {
Pas utilisé non plus

2020-11-13 19:59 UTC, TranTerrence commented on src/pages/FAQPage.tsx
> +  helper: {
pareil pas utilisé

2020-11-13 19:59 UTC, TranTerrence commented on src/pages/FAQPage.tsx
> +  column: {
PAreil pas utilisé

2020-11-13 20:12 UTC, Th-omas reviewed
ok

2020-11-14 18:10 UTC, TranTerrence approved these changes

2020-11-14 18:11 UTC, merged